# Generated by Django 4.1 on 2022-08-24 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inerg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('API_WELL_NUMBER', models.CharField(max_length=200)),
                ('PRODUCTION_YEAR', models.CharField(max_length=100)),
                ('QUARTER', models.CharField(max_length=100)),
                ('OWNER_NAME', models.CharField(max_length=200)),
                ('COUNTRY', models.CharField(max_length=200)),
                ('TOWNSHIP', models.CharField(max_length=200)),
                ('WELL_NAME', models.CharField(max_length=200)),
                ('WELL_NUMBER', models.CharField(max_length=100)),
                ('OIL', models.CharField(max_length=100)),
                ('GAS', models.CharField(max_length=100)),
                ('BRINE', models.CharField(max_length=100)),
                ('DAYS', models.CharField(max_length=100)),
            ],
        ),
    ]
